spring.profiles.active=dev

server.port=8080
spring.main.lazy-initialization=true
spring.jackson.serialization.fail-on-empty-beans=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=health
# ==============================
# AUTH0 CONFIGURATION
# ==============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.apinexo.com/
logging.level.org.springframework.security=INFO

# CORS
spring.security.cors.allowed-methods=*

## Auth0
auth0.client-id=2oZDGYThZBR0ITIXoB5HXsxld3sb0oIs
auth0.client-secret=MD0IDxz-GGGZMnDr-ocbs5GPd9t5_6hLKnAJcv040n78yeCXqpn0-cO1xpBdwXDD
auth0.audience=https://dev-mvjj2ibjsbdpzbm5.us.auth0.com

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=2
spring.redis.lettuce.pool.max-wait=1000