fe.server=
# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://
spring.datasource.username=
spring.datasource.password=
spring.security.cors.allowed-origins=
stripe.secret.key=
stripe.secret.endpoint=