fe.server=https://app.apinexo.com
be.server=https://api.apinexo.com
is.server=true
# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/apinexo
spring.datasource.username=postgres
spring.datasource.password=admin()123456
spring.security.cors.allowed-origins=https://app.apinexo.com
stripe.secret.key=
stripe.secret.endpoint=