fe.server=http://localhost:3000
# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/apinexo
spring.datasource.username=
spring.datasource.password=
spring.security.cors.allowed-origins=http://localhost:3000
stripe.secret.key=
stripe.secret.endpoint=