fe.server=https://app.apinexo.com
be.server=https://api.apinexo.com
# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://database-1.c0h2q88gccn4.us-east-1.rds.amazonaws.com:5432/apinexo
spring.datasource.username=postgres
spring.datasource.password=admin()123456
spring.security.cors.allowed-origins=https://app.apinexo.com
stripe.secret.key=
stripe.secret.endpoint=