openapi: 3.0.0
info:
  title: "Copilot API Documentation"
  description: "Complete reference documentation for the OpenWeb Ninja JSearch API. Includes code examples, data samples, and usage guides for delivering real-time job listings and salary data from public sources and Google for Jobs."
  version: 1.0.0
servers:
  - url: http://localhost:8080/zillow
paths:
  /properties/auto-complete:
    get:
      summary: "properties/auto-complete"
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            example: "Houston"
          description: |
            - Required: true
            - Ex: `Houston`
        - name: cookie
          in: cookie
          schema:
            type: string
          description: |
            - The `cookie` can be copied from browser
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
              example: |
                {
                  "data": [
                    {
                      "display": "Houston, TX",
                      "resultType": "Region",
                      "metaData": {
                        "regionId": 39051,
                        "regionType": "city",
                        "city": "Houston",
                        "county": "Harris County",
                        "state": "TX",
                        "country": "United States",
                        "lat": 29.806592701135212,
                        "lng": -95.39248628329507
                      }
                    },
                    {
                      "display": "Houston, MO",
                      "resultType": "Region",
                      "metaData": {
                        "regionId": 28591,
                        "regionType": "city",
                        "city": "Houston",
                        "county": "Texas County",
                        "state": "MO",
                        "country": "United States",
                        "lat": 37.30385738144349,
                        "lng": -91.95303848691645
                      }
                    },
                    {
                      "display": "Houston, PA",
                      "resultType": "Region",
                      "metaData": {
                        "regionId": 45822,
                        "regionType": "city",
                        "city": "Houston",
                        "county": "Washington County",
                        "state": "PA",
                        "country": "United States",
                        "lat": 40.244438808633824,
                        "lng": -80.22156476807955
                      }
                    },
                    {
                      "display": "Houston, MN",
                      "resultType": "Region",
                      "metaData": {
                        "regionId": 11987,
                        "regionType": "city",
                        "city": "Houston",
                        "county": "Houston County",
                        "state": "MN",
                        "country": "United States",
                        "lat": 43.79500002855346,
                        "lng": -91.58260114203176
                      }
                    },
                    {
                      "display": "Houston, MS",
                      "resultType": "Region",
                      "metaData": {
                        "regionId": 18637,
                        "regionType": "city",
                        "city": "Houston",
                        "county": "Chickasaw County",
                        "state": "MS",
                        "country": "United States",
                        "lat": 33.89424746488277,
                        "lng": -88.96334427925916
                      }
                    }
                  ],
                  "status": true,
                  "message": "Successful"
                }


components:
  securitySchemes:
    X-API-Key:
      type: apiKey
      in: header
      name: x-api-key
      description: API Key
security:
  - X-API-Key: []
